## Task 1
**Notebook files:**
- Task1_sumulation
- Task1_MNIST_GPU

## Task 2
**Notebook files:**
- Task2_PCA
- Task2_grad-norm
- Task2_zero_grad

## Task 3
**Notebook files:**
- Task3_randomLabel
- Task3_Para_VS_Gen
- Task3_flat_VS_gen_part1_lr_1e_2
- Task3_flat_VS_gen_part1_lr_1e_3

**Python file:**
- Task3_Part2.py *(Due to the extended training time, only the code and two generated graphs are provided here.)*

The files `par2-accuracy.png` and `par2-loss.png` were generated by **Task3_Part2.py**.


